# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule: 
    - cron: '45 */1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4

      - name: Install cut-cdn
        run: go install github.com/ImAyrix/cut-cdn@latest

      - name: Get tif.txt
        run: curl -O https://raw.githubusercontent.com/hagezi/dns-blocklists/main/ips/tif.txt

      - name: Run cut-cdn
        run: cut-cdn -ua -a -i ./tif.txt -o ./tifwhitelist.txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Commit message
          commit_message: automatic/regular ip address updates
          file_pattern: ./tif.txt ./tifwhitelist.txt
