# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule: 
    - cron: '0 */1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - name: Install cut-cdn
        run: go install github.com/ImAyrix/cut-cdn@latest

      - name: Install curl
        run: sudo apt install curl

      - name: Get tif.txt
        run: curl -O https://github.com/hagezi/dns-blocklists/raw/main/ips/tif.txt

      - name: Run cut-cdn
        run: cut-cdn -a -i ./tif.txt -o ./tifixed.txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          # Commit message
          commit_message: automatic/regular ip address updates
          file_pattern: ./*.txt
